### ISSUE TITLE
license is invalid!!!

### ISSUE THREAD

**Issue by fanthus** [aliyunvideo/AliPlayerSDK#101]
升级到 5.4.9 之后播放视频会报这种警告（错误？），但不影响视频正常播放，是不是可以忽略？

**Comment by fanthus** [comment]
+-----------------------------------------------------------------------------------------------+
|---------------------------------- license is invalid!!! --------------------------------------|
|---------------------- Please provide correct license key before play, ------------------------|
|------ you can visit 'https://help.aliyun.com/document_detail/434250.html' for more info. -----|
+-----------------------------------------------------------------------------------------------+

**Comment by fanthus** [comment]
看官方文档是需要的，但是这个需要付费吗？

> V5.4.7.1及之后版本的iOS播放器SDK必须按以下操作配置License后，方可使用。
> License配置完成后，查看日志若无License相关报错，则表示License配置成功。

**Comment by fanthus** [comment]
想回退到 5.4.6.0 版本，结果发现官网不支持下载了... https://help.aliyun.com/document_detail/94428.html

**Comment by TheLittleBoy** [comment]
免费申请的哦~

**Comment by TheLittleBoy** [comment]
目前用cocoapods依然可以下载任意版本的哦~

**Comment by fanthus** [comment]
好的哦

**Comment by alyfreym** [comment]
it is possible to free use, if planning to play only local videos?
