### ISSUE TITLE
license is invalid!!!

### ISSUE THREAD

**Issue by alyfreym** [aliyunvideo/AliPlayerSDK#109]
Hi Im planing to use this player only for play local videos. Do I need to pay for it?

When I go to the page -> https://help.aliyun.com/document_detail/434250.html. 

They suggested that <-> connect Log in to the Smart Media Services Console.

But when I click activate button I get this error 
<img width="1716" alt="Screenshot 2023-02-11 at 14 46 29" src="https://user-images.githubusercontent.com/29518174/218251576-71ecaff7-6e7e-41be-b1b5-08f2d440bb7c.png">

Any links how to create license for this player? I could find anything. I searched about ApsaraVideo Player SDK but it seem for remote playing, and there you need to configure domains and so on to obtain a license, but I don't need it, I only need to play local videos. Please help me.

**Comment by TheLittleBoy** [comment]
如果你只是播放本地视频，是不需要申请license的。播放功能是免费使用的。
