### ISSUE TITLE
pod 报错，其他的库都没问题

### ISSUE THREAD

**Issue by yunjinghui123** [aliyunvideo/AliPlayerSDK#29]
Analyzing dependencies
Downloading dependencies
Installing AliPlayerPartSDK_iOS (4.7.4)

[!] Error installing AliPlayerPartSDK_iOS
[!] /usr/bin/git clone https://github.com/aliyunvideo/AliPlayerSDK.git /var/folders/q7/8mz0pcld4t73js_hrlv22s4r0000gn/T/d20200707-10827-om9q5z --template= --single-branch --depth 1 --branch 4.7.4

Cloning into '/var/folders/q7/8mz0pcld4t73js_hrlv22s4r0000gn/T/d20200707-10827-om9q5z'...
fatal: unable to access 'https://github.com/aliyunvideo/AliPlayerSDK.git/': Failed to connect to github.com port 443: Connection refused

**Comment by TheLittleBoy** [comment]
现在GitHub访问速度真的是太慢了，建议官方把source改成git协议，或者把仓库挪到国内git或者阿里的服务器上吧！

**Comment by HuWeiHua1** [comment]
我也是这个错误，不知道怎么解决

**Comment by yunjinghui123** [comment]
我现在将镜像切换到了source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
目前如果多试几次可以更新的下来，也是很慢

**Comment by yunjinghui123** [comment]
也没有什么其他的解决方案，问题关闭了

**Comment by HuWeiHua1** [comment]
好的，谢谢了

发自我的iPhone
