### ISSUE TITLE
只是初始化 Aliplayer 就能让别的 app 音乐停止

### ISSUE THREAD

**Issue by fanthus** [aliyunvideo/AliPlayerSDK#30]
之前的版本没这个问题，更新之后，在其他播放音乐切换到使用阿里云的 APP，音乐就停止了。定位了半天才发现只要初始化 Aliplayer 就会这样.... 这 Aliplayer  的初始化都干了点啥！

临时的解决方案是将 AudioSession  的 isActive 设置为 false.

**Comment by I-m-SuperMan** [comment]
是什么版本？

**Comment by fanthus** [comment]
4.7 的版本。
