### ISSUE TITLE
打包安装后闪退

### ISSUE THREAD

**Issue by dagouzhi** [aliyunvideo/AliPlayerSDK#4]
调试没问题，打包安装后闪退，
```
: DYLD, dependent dylib '/Users/yuanzhan/.emas/build/11643938/workspace/work/apsaraPlayer_demo/Apple/iOS/SDK/Release/AliyunMediaDownloader.framework/AliyunMediaDownloader' not found for '/var/containers/Bundle/Application/538A795F-4110-439E-B14B-26C440C983FE/dgz.app/dgz', tried but didn't find: '/Users/yuanzhan/.emas/build/11643938/workspace/work/apsaraPlayer_demo/Apple/iOS/SDK/Release/AliyunMediaDownloader.framework/AliyunMediaDownloader' '/System/Library/Frameworks/AliyunMediaDownloader.framework/AliyunMediaDownloader'
```

**Comment by xiaopn166** [comment]
遇到跟你一样的问题，希望官方尽快解决

**Comment by hexiao-o** [comment]
pod 集成的吗？我这打包时取消勾选 ReBuild from Bitcode 后打出来的包是可以正常使用，就不知道上架时有问题没！你可以发个去阿里云上发个工单，问问

**Comment by MrHuChun** [comment]
同样的问题，打包上传后通过TestFlight安装后闪退，crash日志如下：
DYLD, Library not loaded: /Users/yuanzhan/.emas/build/12017965/workspace/work/apsaraPlayer_demo/Apple/iOS/SDK/Release/AliyunMediaDownloader.framework/AliyunMediaDownloader | Referenced from: /var/containers/Bundle/Application/34230DAB-A810-4EF9-9ABA-C2FD5E073819/EMD.app/EMD | Reason: image not found

**Comment by MrHuChun** [comment]
已解决。 将Enable Bitcode  改为 NO   （参考demo）

**Comment by firetripod** [comment]
这个问题解决不了么？
