### ISSUE TITLE
请问这四个pod有何区别？

### ISSUE THREAD

**Issue by TheLittleBoy** [aliyunvideo/AliPlayerSDK#5]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/3365421/64099805-c843f580-cd9c-11e9-97a0-ada4bf84477f.png">

有没有文档介绍呢？

**Comment by TheLittleBoy** [comment]
感觉3.x 版本和 4.x版本差距好大啊，有没有升级指南呢？

**Comment by luoei** [comment]
对呀，我也想知道
