### ISSUE TITLE
一启动就崩

### ISSUE THREAD

**Issue by f2yu** [aliyunvideo/AliPlayerSDK#60]
<img width="1612" alt="截屏2021-06-09 下午6 44 44" src="https://user-images.githubusercontent.com/10491688/121340961-c4221000-c952-11eb-8be0-89ca193686df.png">

**Comment by f2yu** [comment]
库冲突导致的\

**Comment by I-m-SuperMan** [comment]
> 库冲突导致的\

是什么库冲突导致的呀？是openssl吗？

**Comment by f2yu** [comment]
是的，BN_num_bits是这个库里面的方法，其他库可能也有这个，但版本不一样，调这个方法调到了ali里面的。当然我没验证过，纯属瞎猜。我的是网易七鱼5.x版本，升到6.x就好了。
