### ISSUE TITLE
Umbrella header for module 'AliyunPlayer' does not include header 'CicadaFrameInfo.h'

### ISSUE THREAD

**Issue by shmy** [aliyunvideo/AliPlayerSDK#91]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/19339440/176069750-542f9f6c-95aa-4d60-8353-7b8965218eb2.png">

版本 `5.4.6.0-24893247` 和 `5.4.7.0` 都不行，请教如何在`swift`内使用啊

**Comment by TheLittleBoy** [comment]
建议多研究研究官方给的OC代码。。。
